Use fixuid and move action to reduce layers impact
- fixuid is perfect to make use of user and group ids from local host
- move common layers on reduce build and push
- better python script to generate versions list
- README has now better explanations, especialy about SELinux
- new Angular versions, rebuilt 6.x to be sure to have latest docker image adaptation

diff --git a/src/Dockerfile b/src/Dockerfile
--- a/src/Dockerfile
+++ b/src/Dockerfile
@@ -1,38 +1,34 @@
 FROM node:10-alpine
 
-RUN apk add --no-cache python git build-base
+RUN apk add --no-cache python git build-base curl
+
+RUN set -xe; \
+  mkdir /app; \
+  chgrp node /app; \
+  chown node /app;
+
+RUN USER=node && \
+    GROUP=node && \
+    curl -SsL https://github.com/boxboat/fixuid/releases/download/v0.4/fixuid-0.4-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf - && \
+    chown root:root /usr/local/bin/fixuid && \
+    chmod 4755 /usr/local/bin/fixuid && \
+    mkdir -p /etc/fixuid && \
+    printf "user: $USER\ngroup: $GROUP\n" > /etc/fixuid/config.yml
 
 ARG VERSION
 RUN set -xe;\
     npm install -g @angular/cli@$VERSION;\
     npm cache clean --force;
 
-
-ARG UID=1001
-ARG GID=0
-
-RUN set -xe; \
-  mkdir /app; \
-  if [ $GID != "0" ]; then \
-    # group is not root \
-    # if GID exists (eg. OSX, gid = 20) \
-    # so we add "node" user to that group either we only change node group to that GID \
-    (grep ":$GID;" /etc/group && sed -i "s/.*:$GID:.*/&,node/") || sed -i 's/1000/'$GID'/g' /etc/group; \
-  fi;\
-  sed -i 's/1000/'$UID'/g' /etc/passwd; \
-  chown -R node:node /home/node; \
-  chgrp $GID /app; \
-  chown $UID /app; \
-  chmod o+r /app;  \
-  chmod g+rwx /app;
-
 WORKDIR /app
-VOLUME /app
-ENV HOME=/tmp APPNAME=hero GENERATE=true
+# Fixuid will fail if we set it as volume
+# VOLUME /app
+
+ENV APPNAME=hero GENERATE=true
 ADD entrypoint.sh /entrypoint.sh
 
 EXPOSE 4200
-USER node
+USER 1000:1000
 
 ENV ANGULAR_VERSION=${VERSION} ANGULAR_STYLESHEET_FORMAT=css ANGULAR_ROUTING=true
 ENTRYPOINT ["/entrypoint.sh"]
